### ISSUE TITLE
Síntesis - Gestión de calidad

### ISSUE THREAD

**Issue by IrvingFernand0** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-IrvingFernand0#1]
[Sintesis_Gestion de calidad.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-IrvingFernand0/files/12704093/Sintesis_Gestion.de.calidad.pdf)

**Comment by mel-16** [comment]
20 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
